minnano_asobi/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :plays
  resources :users
  resources :plays, only: %i[show index] do
    resource :likes, only: %i[create destroy]
  end
  get '/search', to: 'plays#search'
  get '/guest_login', to: 'sessions#guest_login'
  get '/login',      to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'static_page#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

minnano_asobi/app/models/play.rb
# frozen_string_literal: true

class Play < ApplicationRecord
  mount_uploader :play_image_path, PlayImageUploader
  has_many :rules
  has_many :tools
  has_many :likes
  belongs_to :user
  validates_inclusion_of :min_player, :max_player, in: 1..10, message: 'は1~10の間で入力してください'
  validates :title, :outline, :winning_content, presence: true
  validates :min_player, numericality: { less_than_or_equal_to: :max_player }
  validates :max_player, numericality: { greater_than_or_equal_to: :min_player }

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def image_url
    return default_url if play_image_path.nil?

    play_image_path.url
  end

  private

  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    errors.add(:picture, 'should be less than 5MB') if picture.size > 5.megabytes
  end
end

minnano_asobi/app/controllers/plays_controller.rb
# frozen_string_literal: true

class PlaysController < ApplicationController
  before_action :set_play, only: %i[show edit update destroy]
  before_action :logged_in_user, only: %i[show edit update index destroy]

  # GET /plays or /plays.json
  def index
    # @plays = Play.all
    @plays = Play.paginate(page: params[:page])
  end

  # GET /plays/1 or /plays/1.json
  def show; end

  # GET /plays/new
  def new
    @play = Play.new
  end

  # GET /plays/1/edit
  def edit; end

  # POST /plays or /plays.json
  def create
    @play = Play.new(play_params)
    @tool = Tool.new(tool_params[:tool])
    respond_to do |format|
      if @play.save
        @tool.play_id = @play.id
        @tool.save
        rule_params.each do |_tmp, rule_hash|
          @rule = Rule.new(rule_content: rule_hash['content'], rule_image_path: rule_hash['image'])
          @rule.play_id = @play.id
          @rule.save
        end
        format.html { redirect_to @play, notice: 'Play was successfully created.' }
        format.json { render :show, status: :created, location: @play }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plays/1 or /plays/1.json
  def update
    @tool = Tool.find_by(play_id: params[:id])
    @rule = Rule.where(play_id: params[:id])
    respond_to do |format|
      if @play.update(play_params)
        # toolについて
        if !@tool.nil?
          @tool.update(tool_params[:tool])
        else
          @tool = Tool.new(tool_params[:tool])
          @tool.play_id = @play.id
          @tool.save
        end
        # ruleについて
        if @rule.length != rule_params.length
          @rule.each(&:destroy)
          rule_params.each do |_tmp, content_hash|
            @rule = Rule.new(rule_content: content_hash['content'], rule_image_path: content_hash['image'])
            @rule.play_id = @play.id
            @rule.save
          end
        else
          @rule.zip(rule_params).each do |rule, rule_hash|
            if rule_hash[1]['image'].present?
              rule.update(rule_content: rule_hash[1]['content'], rule_image_path: rule_hash[1]['image'])
            else
              rule.update(rule_content: rule_hash[1]['content'])
            end
          end
        end
        format.html { redirect_to @play, notice: 'Play was successfully updated.' }
        format.json { render :show, status: :ok, location: @play }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plays/1 or /plays/1.json
  def destroy
    @play.destroy
    respond_to do |format|
      format.html { redirect_to plays_url, notice: 'Play was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @plays = Play.where(title: params[:title]).paginate(page: params[:page])
                 .or(Play.where(place: params[:place]).paginate(page: params[:page]))
                 .or(Play.where(min_player: params[:min_player]).paginate(page: params[:page]))
                 .or(Play.where(max_player: params[:max_player]).paginate(page: params[:page]))
    if params[:title].eql?('') && params[:place].eql?('') && params[:min_player].eql?('') && params[:max_player].eql?('')
      @plays = Play.paginate(page: params[:page])
    end
    respond_to do |format|
      format.html { render :index }
      format.json { render :index, status: :ok, location: @play }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_play
    @play = Play.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def play_params
    params.require(:play).permit(:title, :place, :outline, :winning_content, :min_player, :max_player, :user_id, :play_image_path, :deleted_at)
  end

  # Only allow a list of trusted parameters through.
  def tool_params
    params.require(:play).permit(tool: [:tool_content])
  end

  def rule_params
    params.require(:rule).permit!.to_hash
  end
end

minnano_asobi/app/helpers/plays_helper.rb
# frozen_string_literal: true

module PlaysHelper
end

minnano_asobi/app/views/plays/_form.html.erb
<%= form_with(model: play, local: true) do |form| %>
  <% if play.errors.any? %>
    <div id="error_explanation">
      <h2><%= play.errors.count %>件のエラーが発生しました</h2>

      <ul>
        <% play.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :play_image_path, "遊びのイメージ図" %>
    <br>
    <%= form.file_field :play_image_path %>
  </div>

  <div class="field mb-3">
    <%= form.label :min_player, "最小人数" %>
    <%= form.number_field :min_player, class: "form-control"%>
  </div>

  <div class="field mb-3">
    <%= form.label :max_player, "最大人数" %>
    <%= form.number_field :max_player, class: "form-control"%>
  </div>

  <div class="field mb-3">
    <%= form.label :place, "場所" %>
    <%= form.text_field :place, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.fields_for :tool do |tool| %>
      <%= tool.label :tool_content, "道具" %>
      <% unless play.tools.empty? %>
        <%= tool.text_area :tool_content, value: play.tools[0].tool_content, class: "form-control" %>
      <% else %>
        <%= tool.text_area :tool_content, class: "form-control" %>
      <% end %>
    <% end %>
  </div>

  <div class="field mb-3">
    <%= form.label :outline, "概要" %>
    <%= form.text_area :outline, class: "form-control" %>
  </div>

  <div class="field">
    <%#= form.label :user_id %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%#= form.label :deleted_at %>
    <%#= form.datetime_select :deleted_at %>
  </div>

    <div class="field mb-3">
      <%= form.fields_for :rule do |rule| %>
        <div class="rule-form">
          <% if play.rules.empty? %>
            <div class="rule-list">
              <%= rule.label :rule_content, "ルール" %>
              <%= rule.text_area :rule_content, name: "rule[rule_content0][content]", class: "form-control" %>
              <%= rule.file_field :rule_image_path, name: "rule[rule_content0][image]" %>
              <button type="button" class="delete-form-btn btn btn-danger">このルールを削除</button>
            </div>
          <% else %>
            <% play.rules.each_with_index do |rule_form, index|%>
              <div class="rule-list">
                <%= rule.label :rule_content, "ルール" %>
                <%= rule.text_area :rule_content, name: "rule[rule_content#{index}][content]", value: rule_form.rule_content, class: "form-control" %>
                <%= rule.file_field :rule_image_path, name: "rule[rule_content#{index}][image]", value: rule_form.rule_image_path %>
                <button type="button" class="delete-form-btn btn btn-danger">このルールを削除</button>
              </div>
            <% end %>
          <% end %>
        </div>
        <div class="text-danger">
          ルールを修正する場合は、画像を再アップロードしてください。
        </div>
      <% end %>
      <button type="button" class="add-form-btn btn btn-primary">ルールを追加</button>
    </div>
  
  <div class="field mb-3">
    <%= form.label :winning_content, "勝利条件" %>
    <%= form.text_area :winning_content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "登録", class: "btn btn-success center" %>
  </div>
<% end %>

minnano_asobi/app/views/plays/_rule_card.html.erb
<div class="card  mb-3">
  <div class="row no-gutters">
    <div class="col-lg-6">
      <span class="img"><%= image_tag rule.image_url, size: '200x200' %></span>
    </div>
    <div class="col-lg-6">
      <div class="card-body">
        <p class="card-text"><%= rule.rule_content %></p> 
      </div>
    </div>
  </div>
</div>

minnano_asobi/app/views/plays/edit.html.erb
<h4>遊びの修正</h4>

<%= render 'form', play: @play %>

<%= link_to '戻る', @play %>
<%#= link_to '戻る', plays_path %>

minnano_asobi/app/views/plays/index.html.erb
<p id="notice"><%= notice %></p>

<div class="order-md-1">
  <h4 class="title mb-3">遊び一覧</h4>

  <div class="search">
    <%= form_with(model: @play, url: search_path, method: :get, local: true) do |form| %>
      <div class="field mb-3">
        <%= form.label :title, "タイトル" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="field mb-3">
        <%= form.label :place, "場所" %>
        <%= form.text_field :place, class: "form-control" %>
      </div>
      <div class="field mb-3">
        <%= form.label :min_player, "最小人数" %>
        <%= form.number_field :min_player, class: "form-control" %>
      </div>

      <div class="field mb-3">
        <%= form.label :max_player, "最大人数" %>
        <%= form.number_field :max_player, class: "form-control" %>
      </div>
      <div class="actions mb-3">
        <%= form.submit "検索", class: "btn btn-success center" %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <hr class="py-0 my-4 my-sm-5">
  </div>
</div>

<%= will_paginate %>

<div class="index">
  <% @plays.each do |play| %>
    <%= link_to play_path(play) do %>
      <%= render 'cards/card', play: play %>
    <% end %>
  <% end %>
</div>

<%= will_paginate %>

<br>

<%#= link_to 'New Play', new_play_path %>

minnano_asobi/app/views/plays/new.html.erb
<p></p>
<div class="order-md-1">
  <h4 class="title mb-3">遊びを投稿</h4>

  <%= render 'form', play: @play %>
</div>
<%#= link_to 'Back', plays_path %>

minnano_asobi/app/views/plays/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @play.title %></h1>
<h2><%= @play.user.name %><%= image_tag @play.user.image_url, size: '50x50' %></h2>

<!--  -->
<div>
  <%= image_tag @play.image_url, size: "200x200" %>
</div>

<div class="row">
  <%= time_ago_in_words(@play.updated_at) %>前に更新
</div>

<div class="row">
  <div class="col-12">
    <hr class="py-0 my-4 my-sm-5">
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <h4 class="mb-4">遊べる人数</h4>
  </div>
  <div class="col-lg-8">
    <% if @play.min_player == @play.max_player %>
      <%= @play.min_player %> 人
    <% else %>
      <%= @play.min_player %> ~ <%= @play.max_player %> 人
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <hr class="py-0 my-4 my-sm-5">
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <h4 class="mb-4">場所</h4>
  </div>
  <div class="col-lg-8">
    <%= @play.place %>  
  </div>
</div>

<div class="row">
  <div class="col-12">
    <hr class="py-0 my-4 my-sm-5">
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
      <h4 class="mb-4">道具</h4>
    </div>
    <div class="col-lg-8">
        <%= @play.tools[0].tool_content if @play.tools[0] != nil %>
    </div>
</div>

<div class="row">
  <div class="col-12">
    <hr class="py-0 my-4 my-sm-5">
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <h4 class="mb-4">概要</h4>
  </div>
  <div class="col-lg-8">
    <%= @play.outline %>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <hr class="py-0 my-4 my-sm-5">
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <h4 class="mb-4">勝利条件</h4>
  </div>
  <div class="col-lg-8">
    <%= @play.winning_content %>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <hr class="py-0 my-4 my-sm-5">
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <h4 class="mb-4">手順</h4>
  </div>
  <div class="col-lg-8">
    <% @play.rules.each do |rule| %>
      <%= render 'rule_card', rule: rule %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <hr class="py-0 my-4 my-sm-5">
  </div>
</div>

<% if current_user == @play.user %>
  <%= link_to '修正', edit_play_path(@play), data: {"turbolinks" => false} %> |
<% end %>
<%= link_to '戻る', plays_path %>