minnano_asobi/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :plays
  resources :users
  resources :plays, only: %i[show index] do
    resource :likes, only: %i[create destroy]
  end
  get '/search', to: 'plays#search'
  get '/guest_login', to: 'sessions#guest_login'
  get '/login',      to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'static_page#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

minnano_asobi/app/views/layouts/_header.html.erb
<!--<header class="navbar navbar-fixed-top navbar-inverse navbar-expand">-->
<header>
  <nav class="navbar navbar-expand-lg navbar-light justify-content-center" style="background-color: #e3f2fd;">
    <div>
      <%= link_to "みんなの遊び", root_path, id: "logo", class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
            <% if logged_in? %>
              <li class="nav-item"><%= link_to "遊び一覧", plays_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "遊びを投稿", new_play_path, data: {"turbolinks" => false}, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to 'ユーザー一覧', users_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to current_user, class: "nav-link" do %>
                <%= "#{current_user.name}さん" %>
                <%= image_tag current_user.image_url, size: "50x50" %>
                <% end %>
              </li>
              <li class="nav-item"><%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link btn btn-danger" %></li>
            <% else %>
              <li class="nav-item"><%= link_to "ログイン", login_path, data: {"turbolinks" => false}, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "ゲストログイン", guest_login_path, data: {"turbolinks" => false}, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "会員登録", new_user_path, class: "nav-link" %></li>
            <% end %>
          </ul>
      </div>
    </div>
  </nav>
</header>

minnano_asobi/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MinnanoAsobi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="row">
      <div class="col-md-8 col-md-offset-3 mx-auto">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>