minnano_asobi/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :plays
  resources :users
  resources :plays, only: %i[show index] do
    resource :likes, only: %i[create destroy]
  end
  get '/search', to: 'plays#search'
  get '/guest_login', to: 'sessions#guest_login'
  get '/login',      to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'static_page#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

minnano_asobi/app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :play

  # 同じ投稿を複数回お気に入り登録させないため
  validates_uniqueness_of :play_id, scope: :user_id
end

minnano_asobi/app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :logged_in_user
  before_action :set_play

  def create
    if @play.user_id != current_user.id
      @like = Like.create(user_id: current_user.id, play_id: @play.id)
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_url) }
        format.js
      end
    end
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, play_id: @play.id)
    @like.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_url) }
      format.js
    end
  end

  private

  def set_play
    @play = Play.find(params[:play_id])
  end
end

minnano_asobi/app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

minnano_asobi/app/views/likes/_like.html.erb
      <% if current_user.id != play.user_id %>
        <% if play.liked_by?(current_user) %>
          <p><%= link_to play_likes_path(play), method: :delete, remote: true do %>
            <i class="fas fa-star unlike-btn"></i>
            <%= play.likes.count %>
            <% end %>
          </p>
        <% else %>
          <p><%= link_to play_likes_path(play), method: :post, remote: true do %>
            <i class="far fa-star like-btn"></i>
            <%= play.likes.count %>
            <% end %>
          </p>
        <% end %>
      <% else %>
        <p>
          <i class="fas fa-star unlike-btn"></i>
          <%= play.likes.count %>
        </p>        
      <% end %>

minnano_asobi/app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

minnano_asobi/app/views/likes/create.js.erb
$('#like-btn-<%= @play.id %>').html("<%= escape_javascript(render partial: "likes/like", locals: { play: @play }) %>");

minnano_asobi/app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

minnano_asobi/app/views/likes/destroy.js.erb
$('#like-btn-<%= @play.id %>').html("<%= escape_javascript(render partial: "likes/like", locals: { play: @play }) %>");