minnano_asobi/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :plays
  resources :users
  resources :plays, only: %i[show index] do
    resource :likes, only: %i[create destroy]
  end
  get '/search', to: 'plays#search'
  get '/guest_login', to: 'sessions#guest_login'
  get '/login',      to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'static_page#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

minnano_asobi/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  mount_uploader :user_image_path, UserImageUploader
  has_many :likes
  has_many :plays
  attr_accessor :remember_token

  validates :name,
            presence: true,
            length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email,
            presence: true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
            BCrypt::Engine::MIN_COST
          else
            BCrypt::Engine.cost
          end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update(remember_digest: User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update(remember_digest: nil)
  end

  def image_url
    return default_url if user_image_path.nil?

    user_image_path.url
  end

  private

  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    errors.add(:picture, 'should be less than 5MB') if picture.size > 5.megabytes
  end
end

minnano_asobi/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[edit update index destroy]
  before_action :correct_user, only: %i[edit update]
  before_action :set_user, only: [:show]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: "User was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :user_image_path)
  end

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

minnano_asobi/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

minnano_asobi/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= user.errors.count %>件のエラーが発生しました</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= form.label :user_image_path, value: "アイコン" %>
    <br>
    <%= form.file_field :user_image_path %>
  </div>

  <div class="actions mb-3">
    <%= form.submit class: "btn btn-primary", value: "会員登録" %>
  </div>
<% end %>

minnano_asobi/app/views/users/_likes.html.erb
<div class="index">
  <% @user.likes.each do |like| %>
      <%= link_to play_path(like.play) do %>
        <%= render 'cards/card', play: like.play %>
      <% end %>
  <% end %>
</div>

minnano_asobi/app/views/users/_posted.html.erb
<div class="index">
  <% @user.plays.each do |play| %>
      <%= link_to play_path(play) do %>
        <%= render 'cards/card', play: play %>
      <% end %>
  <% end %>
</div>

minnano_asobi/app/views/users/edit.html.erb
<h4>ユーザー情報の修正</h4>

<%= render 'form', user: @user %>

<%= link_to '戻る', @user %>
<%#= link_to 'ユーザー一覧', users_path %>

minnano_asobi/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h4>ユーザー一覧</h4>

<table>
  <thead>
    <tr>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user do %><%= image_tag user.image_url, size: '50x50' %><%= user.name %><% end %></td>
        <% if user.id == current_user.id %>
          <td><%= link_to 'ユーザー情報の修正', edit_user_path(user) %></td>
          <td><%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New User', new_user_path %>

minnano_asobi/app/views/users/new.html.erb
<h4>会員登録</h4>

<%= render 'form', user: @user %>

minnano_asobi/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <% if current_user == @user %>
  <strong>Email:</strong>
    <%= @user.email %>
  <% end %>
</p>

<p>
  <strong>アイコン:</strong>
  <%= image_tag @user.image_url, size: '50x50' %>
</p>

<p>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="list-group-item list-group-item-action active" data-toggle="list" href="#plays" role="tab">投稿</a>
    </li>
    <li class="nav-item">
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#likes" role="tab">お気に入り</a>
    </li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="plays" role="tabpanel">
      <%= render 'posted', user: @user %>
    </div>
    <div class="tab-pane" id="likes" role="tabpanel">
      <%= render 'likes', user: @user %>
    </div>
  </div>


</p>

<% if current_user == @user %>
  <%= link_to 'ユーザー情報の修正', edit_user_path(@user), class: "btn btn-secondary" %>  
<% end %>
<%#= link_to 'ユーザー一覧', users_path %>